### PR TITLE
Fix the ordering of callbacks using process.nextTick

### LINKED ISSUE #9: Fix callback ordering
see https://github.com/pebble/pebble-api-node/pull/6/files#r28114561

### PR DESCRIPTION
**Pull request by matthewtole**
Fixes #9.

### CODE REVIEW

File: lib/timeline.js [hunk 1]
```diff
@@ -31,7 +31,8 @@ Timeline.Pin = Pin;
  */
 Timeline.prototype.sendUserPin = function (userToken, pin, callback) {
   if (typeof userToken !== 'string') {
-    return callback(new Error('Expected userToken to be a string.'));
+    process.nextTick(callback(new Error('Expected userToken to be a string.')));
```
Comment (aheckmann) [inline lib/timeline.js]: this will still execute the callback immediately. we'll need smth like

```js
return process.nextTick(function(){
  callback(new Error(..))
});
```

Comment (matthewtole) [inline lib/timeline.js]: Yeah. I don't know what I was thinking. I appear to have lost the ability to JavaScript properly. Too much time spent doing Ruby I think.

Comment (jlai) [inline lib/timeline.js]: This looks like it would call process.nextTick on the return value of the callback

**Comment by aheckmann** [comment]
should bump the minor for this due to behavior change

**Comment by matthewtole** [comment]
There is another PR incoming shortly from @Neal, I was going to group these two together under a single version change.

**Comment by aheckmann** [comment]
there will likely be another one in the next few days too before next Thur

On Friday, April 24, 2015, Matthew Tole <notifications@github.com> wrote:

> There is another PR incoming shortly from @Neal <https://github.com/Neal>,
> I was going to group these two together under a single version change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pebble/pebble-api-node/pull/11#issuecomment-96038898>.
>


-- 
Aaron Heckmann
Web Development Lead :: Pebble
https://github.com/aheckmann
https://twitter.com/aaronheckmann
